### ISSUE TITLE
Creating project from console does not take name into account

### ISSUE THREAD

**Issue by marekpaprota** [versioneye/versioneye#621]
@reiz  I'm trying to create project using version eye api console. I'm choosing .sbt file and assigning some name. In response I get name of the project like the name of the file (default behavior). The same is with nodejs package.json file

![wrong_name](https://cloud.githubusercontent.com/assets/17719823/16949528/9666af58-4dbb-11e6-9a09-d8a5bc3da3d1.png)

**Comment by reiz** [comment]
Hi @marekpaprota. The API itself is working fine. There are several unit tests which test the name setting as well. Here is such a test case: https://github.com/versioneye/versioneye-api/blob/master/spec/api/v2/projects_api_spec.rb#L197-L213. 

It's not working for you because there is a bug in SwaggerUI. Please try the upload via Curl. I just uploaded a new file with this Curl command and it worked: 

```
curl -F name=my_test_name -F orga_name=MYORGA -F team_name=Owners -F upload=@build.sbt "https://www.versioneye.com/api/v2/projects?api_key=YOUR_API_KEY"
```

There is a newer version of SwaggerUi available which fixed this issue and it will be updated in VersionEye soon, but not in the next 2 weeks.

Let me now if it works for you via CURL. If not please reopen this ticket.

**Comment by reiz** [comment]
@marekpaprota By the way. For Scala SBT projects I recommend to use the VersionEye SBT Plugin: https://github.com/versioneye/versioneye_sbt_plugin. That's using the VersionEye API but has some additional features.
