### ISSUE TITLE
Allow multiple versions

### ISSUE THREAD

**Issue by kyuff** [versioneye/versioneye#631]
Feature:
In a large development organization people will work on several branches at the same time. There is a need for two different branches to be able to verify license violations in parallel.

Scenario:
Using Git for VCS and Maven for build tool, a CI server builds two different branches and as part of it runs mvn versioneye:update on their seperate branches at the same time.
One of the branches violates the license rules and should fail the build accordingly. The other should not.

One solution could be that each build sets the version according to the branch name. Thus a developer could go to versioneye.com and see the application and sort by version to find the failed build.

**Comment by reiz** [comment]
Hi @kyuff There are 2 solutions for that.

### Integration with the CI server
You can run on each build the VersionEye Maven Plugin:

```
mvn versioneye:licenseCheck
```

That will build your break if there is a license violations. The same works with other plugins for Gradle, SBT and NPM. 

### Pull Request Integration

Since last week we have support for pull requests. Now VersionEye can check your dependencies on each pull request. Currently the checks work for security vulnerabilities and unknown licenses. Support for license whitelist violations is coming in the next days.

**Comment by cdeszaq** [comment]
@reiz how does the PR integration work in concert with the maven plugin? Is the general setup expected to be something like:

1. Maven plugin that runs `mvn versioneye:update` on release / merge-to-master builds
2. Maven plugin running `mvn versioneye:licenseCheck` on PR builds and TravisCI builds
3. PR hook set up for getting updates on PRs

In a nutshell, I guess I'm looking for a "recipe" or a "best practices" guide for using Version Eye with an Open Source multi-module maven project on GitHub. If you have something like that (or could toss together a blog post 😉) that would be fantastic!

**Comment by farhanible** [comment]
This is fairly old now but, replying since it may help others who search this up. The PR integration will add a failed check status on PRs, which will be shown within the Github PR interface. Someone with admin privileges on the repo will have to override the failed check to merge that PR.

CC: @reiz for confirmation

**Comment by reiz** [comment]
Hi @farhanible thanks for bringing this up. The pull request integration is always looking for security vulnerabilities in the dependencies and for dependencies with no license or with a "bad" license. If that is the case the whole pull request will be marked as failed. However since today there is an option to ignore licenses on pull requests. In that case VersionEye will check security vulnerabilities only! 

@cdeszaq For Maven multi module projects I always recommend to use the VersionEye Maven Plugin on CI servers. That plugin is always updating your VersionEye project and based on the Maven goal the plugin can break your build if there is a security vulnerability or a license violation. 
The pull request integration works well for dynamic languages like Ruby, Python, Node.JS and so on, but it never updates your exiting project. It's always a temporary check on each change of the pull request. 

I hope that clarifies the situation. Any more questions?
