### ISSUE TITLE
add pyenv, and allow adding projects that aren't yours

### ISSUE THREAD

**Issue by jab** [versioneye/versioneye#641]
I searched VersionEye for pyenv, hoping to find https://github.com/yyuu/pyenv (which should have been the [top result](https://www.google.com/search?q=pyenv)), but it wasn't there, and instead a lot of much less relevant results were. So I clicked the green + Add Project link in the topnav and was taken to https://www.versioneye.com/projects/new, but that workflow seems to only allow adding my own projects; there seems to be no way for me to add https://github.com/yyuu/pyenv. Could you please add it, and allow users to add projects that aren't theirs?

**Comment by reiz** [comment]
Here we go https://www.versioneye.com/shell/pyenv/v20160726 :-)

**Comment by jab** [comment]
Thanks @reiz. This issue is also for allowing users to add projects that don't belong to them. Is that possible now?

**Comment by reiz** [comment]
@jab If you search for a product which doesn't return any results you can suggest a new product. For example through this search: https://www.versioneye.com/search?q=suggest_a_new_product. The the URL leads to an existing GitHub repository I can approve it quiet fast because we have a crawler for that.

**Comment by jab** [comment]
Oh excellent, thanks @reiz and great work!
