### ISSUE TITLE
Component Whitelist for Javascript modules

### ISSUE THREAD

**Issue by bkimminich** [versioneye/versioneye#642]
I am trying to turn off complaints about `UNKNOWN` license for some modules and have created a component whitelist for that: https://www.versioneye.com/organisations/bkimminich_orga/component_whitelists/default

No matter how I enter the components, on every re-parse I still get the complaints about `UNKNOWN` license:

```
javascript:twbs/bootstrap:3.3.7
javascript:twbs/bootstrap
twbs:bootstrap
bootstrap
```

I'm happy for any suggestions and corresponding update of the documentation for non-Java components `LANGUAGE : PROD_KEY : VERSION`.

**Comment by herodrigues** [comment]
Language for Bootstrap is Node.JS: https://www.versioneye.com/Node.JS/bootstrap/3.3.7

So you should use Node.JS:bootstrap:3.3.7

**Comment by reiz** [comment]
Hi @bkimminich @herodrigues Sorry for the late response. That problem was just solved here: https://blog.versioneye.com/2017/01/31/simplified-component-whitelist/. Now you can put a dependency to your component whitelist by simply clicking the + icon directly next to the dependency. 

![screen shot 2017-01-31 at 16 35 11](https://cloud.githubusercontent.com/assets/652130/22472441/efc00400-e7d5-11e6-8589-4356a1608046.png)
