### ISSUE TITLE
Pricing and implementation is inconsistent

### ISSUE THREAD

**Issue by stefan-kolb** [versioneye/versioneye#649]
Current pricing says:
![image](https://cloud.githubusercontent.com/assets/2141507/19973043/506a4276-a1e4-11e6-8739-806018cf3468.png)

However, when I try to add a second project (it is private, there already is 1 public project), I get an alert:
![image](https://cloud.githubusercontent.com/assets/2141507/19973092/8656c17a-a1e4-11e6-8727-cb72c65ff988.png)

**Comment by reiz** [comment]
Hi @stefan-kolb I can't reproduce it. Are you sure that the other one was a public project? Up to now it was not obvious which VersionEye project was private/public. That's why I just updated the project index view. If a project is private it's marked with a lock icon. Projects where the visibility is limited to collaborators only are marked with an broken eye icon. 

<img width="760" alt="screen shot 2017-01-12 at 14 38 59" src="https://cloud.githubusercontent.com/assets/652130/21891919/4c8f669a-d8d5-11e6-8ed6-fc6bd2d8c4e2.png">

In the image above the first 2 projects are private, because they have been created through the API. That's why they are marked with a lock icon. 

If this issue still exists for you feel free to reopen this ticket and please post a link to your organisation, so that I can start to debug it.

**Comment by stefan-kolb** [comment]
Is fixed now.
