### ISSUE TITLE
False unknown dependencies

### ISSUE THREAD

**Issue by MaChristmann** [versioneye/versioneye#692]
Just noticed that on this package
https://www.versioneye.com/javascript/yyx990803:vue/2.3.4#dependencies

there are  a lot of dependencies that appear to be unknown to VE 
like: selenium-server | ^2.53.1 | UNKNOWN

In fact i tested it for the above package and it is known to VE
like: https://www.versioneye.com/nodejs/selenium-server/3.4.0

**Comment by reiz** [comment]
Hi @MaChristmann The package from the first link is a package from Bower.io. Your 2nd link leads to a NodeJS package from NPM. That are 2 different package managers. We resolve dependencies always inside of a package manager, because that's the way your native package manager works as well. In generell I would recommend NOT to use bower anymore. It's not very good and in the mean while you can replace it through NPM. The NPM solution is much more robust and has a much better API than bower.io.
